apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: mobile-api
spec:
  provider:
    gcpsm:
      projectID: devops-435706
      auth:
        workloadIdentity:
          clusterLocation: europe-north1-c
          clusterName: mobile-api-stage-cluster
          clusterProjectID: devops-435706
          serviceAccountRef:
            name: external-secret-ksa
            namespace: mobile-api
