apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: mobile-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: 'true'
      containers:
        - name: auth-service
          image: <<KUSTOMIZE ME>>
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_VALUE
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: auth-service-secret
          resources:
            requests:
              memory: '128Mi' # Minimum memory guaranteed to the container
              cpu: '250m' # Minimum CPU guaranteed to the container (0.25 of a CPU)
            limits:
              memory: '256Mi' # Maximum memory the container can use
              cpu: '500m' # Maximum CPU the container can use (0.5 of a CPU)
          volumeMounts:
            - name: secrets-volume
              mountPath: '/etc/secrets'
              readOnly: true
      volumes:
        - name: secrets-volume
          secret:
            secretName: auth-service-secret
