apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secret
  namespace: mobile-api
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: auth-service-secret #this will create in the cluster
  data:
    - secretKey: auth-service-secret
      remoteRef:
        key: auth-service-secret
        version: latest
