name: Build and Push Docker Images

on:
  push:
    branches:
      - '**'
    paths:
      - 'services/auth-service/**'
      - 'services/payment-service/**'
      - 'services/finance-service/**'
      - 'services/status-service/**'

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensure enough history is fetched for git diff to work

      - name: Check for Changes in Directory
        id: check_changes
        run: |
          echo "Checking changes in services/auth-service/..."
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^services/auth-service/'; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Skip Steps if No Changes
        if: env.changes == 'false'
        run: echo "No changes detected in services/auth-service/. Skipping subsequent steps."

      - name: Proceed with Actions
        if: env.changes == 'true'
        run: echo "Changes detected. Proceeding with the workflow..."

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure GCR Docker credentials
        run: echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build Docker Image for Auth Service
        run: |
          docker build --build-arg service_name=auth-service -t gcr.io/devops-435706/auth-service:latest .
          docker push gcr.io/devops-435706/auth-service:latest


