name: Build and Push Docker Images

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

jobs:
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.services }}
      root_changed: ${{ steps.filter.outputs.root_changed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history for accurate diff

      - name: Filter Changed Paths
        id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            services:
              - 'services/**'
            root_changed:
              - '!(services/**)'  # Match everything except the 'services/' directory

  build-auth:
    needs: filter-changes
    if: contains(needs.filter-changes.outputs.services, 'auth-service') || needs.filter-changes.outputs.root_changed == 'true'
    uses: ./.github/workflows/docker-build-and-push.yaml
    with: 
      docker_build_args: "service_name=auth-service"
      dockerfile_path: "./Dockerfile"
      docker_context: "."
      image_name: "gcr.io/devops-435706/auth-service:${{ github.sha }}"
      trivy_scan: false
    secrets: inherit

  build-finance:
    needs: filter-changes
    if: contains(needs.filter-changes.outputs.services, 'finance-service') || needs.filter-changes.outputs.root_changed == 'true'
    uses: ./.github/workflows/docker-build-and-push.yaml
    with: 
      docker_build_args: "service_name=finance-service"
      dockerfile_path: "./Dockerfile"
      docker_context: "."
      image_name: "gcr.io/devops-435706/finance-service:${{ github.sha }}"
      trivy_scan: false
    secrets: inherit

  build-payment:
    needs: filter-changes
    if: contains(needs.filter-changes.outputs.services, 'payment-service') || needs.filter-changes.outputs.root_changed == 'true'
    uses: ./.github/workflows/docker-build-and-push.yaml
    with: 
      docker_build_args: "service_name=payment-service"
      dockerfile_path: "./Dockerfile"
      docker_context: "."
      image_name: "gcr.io/devops-435706/payment-service:${{ github.sha }}"
      trivy_scan: false
    secrets: inherit

  build-status:
    needs: filter-changes
    if: contains(needs.filter-changes.outputs.services, 'status-service') || needs.filter-changes.outputs.root_changed == 'true'
    uses: ./.github/workflows/docker-build-and-push.yaml
    with: 
      docker_build_args: "service_name=status-service"
      dockerfile_path: "./Dockerfile"
      docker_context: "."
      image_name: "gcr.io/devops-435706/status-service:${{ github.sha }}"
      trivy_scan: false
    secrets: inherit
    



