name: Build and Push Docker Images

on:
  push:
    branches:
      - '**'
    paths:
      - 'services/auth-service/**'
      - 'services/payment-service/**'
      - 'services/finance-service/**'
      - 'services/status-service/**'

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensure enough history is fetched for git diff to work

      - name: Check for Changes in Services
        id: check_changes
        run: |
          # Initialize an empty list to track updated services
          UPDATED_SERVICES=""
          
          # Check for changes in each service directory
          for service in services/*/; do
            service_name=$(basename $service)
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^${service}"; then
              UPDATED_SERVICES="${UPDATED_SERVICES} ${service_name}"
            fi
          done
          
          # If any services were updated, save them as an environment variable
          if [ -n "$UPDATED_SERVICES" ]; then
            echo "UPDATED_SERVICES=$UPDATED_SERVICES" >> $GITHUB_ENV
            echo "Changes detected in the following services: $UPDATED_SERVICES"
          else
            echo "No changes detected in any services."
            echo "UPDATED_SERVICES=" >> $GITHUB_ENV
          fi

  deploy-auth:
    needs: check-for-changes  # This job depends on the check-for-changes job
    if: ${{ contains(env.UPDATED_SERVICES, 'auth-service') }}  # Only run this job if auth-service is updated
    uses: ./shared/docker-build-and-push.yaml
    with: 
      docker_build_args: "service_name=auth-service"
      dockerfile_path: "./Dockerfile"
      docker_context: "."
      image_name: "gcr.io/devops-435706/finance-service:${{ github.sha }}"
    

      # cant use reusable workflow as a step
      # - name: Run shared workflow
      #   uses: ./.github/workflows/shared/docker-build-and-push.yaml
      #   with: 
      #     docker_build_args: "service_name=auth-service"
      #     dockerfile_path: "./Dockerfile"
      #     docker_context: "."
      #     image_name: "gcr.io/devops-435706/finance-service:${{ github.sha }}"

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Authenticate to GCP
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.GCP_SA_KEY }}

      # - name: Authenticate to Google Container Registry
      #   run: |
      #     gcloud auth configure-docker

      # - name: Build Docker Image for Auth Service
      #   run: |
      #     docker build --build-arg service_name=auth-service -t gcr.io/devops-435706/auth-service:latest .
      #     docker push gcr.io/devops-435706/auth-service:latest


